name: LoginNotify
version: '1.4'
author: Totilak
contributors: [WesOrangePower]
main: ru.edenor.loginNotify.LoginNotify
description: The plugin allows you to notify the administration when marked players log in
api-version: '1.21.8'
softdepend: [ Matrix, EdenorWarnings ]
folia-supported: true
permissions:
  loginnotify.notify:
    description: Получать уведомления о входе
  loginnotify.edit:
    description: Добавлять и удалять игроков
  loginnotify.list:
    description: Просматривать список
  loginnotify.reload:
    description: Перезагружать плагин
  loginnotify.matrixToggle:
    description: Отключить сообщения от Matrix